# Generated by Django 4.2 on 2023-04-20 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RECategory',
            fields=[
                ('ctgid', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WCategory',
            fields=[
                ('ctgid', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Description', models.TextField()),
                ('Examples', models.TextField()),
                ('Summary', models.TextField()),
                ('Catg', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webhook.recategory')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('exid', models.IntegerField(primary_key=True, serialize=False)),
                ('Task', models.TextField()),
                ('Content', models.TextField()),
                ('Answer', models.TextField()),
                ('Catg', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webhook.recategory')),
            ],
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('wid', models.IntegerField(primary_key=True, serialize=False)),
                ('WordForeign', models.TextField()),
                ('WordRussian', models.TextField()),
                ('Catg', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webhook.wcategory')),
            ],
        ),
    ]
