# Generated by Django 4.2 on 2023-05-01 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0003_exercise_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('upk', models.IntegerField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='dictionary',
            name='word_uid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='webhook.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wcategory',
            name='ctg_uid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='webhook.user'),
            preserve_default=False,
        ),
    ]
