# Generated by Django 4.2 on 2023-05-01 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0004_user_dictionary_word_uid_wcategory_ctg_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='word_uid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='webhook.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wcategory',
            name='ctg_uid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='webhook.user'),
        ),
    ]
