# Generated by Django 4.2 on 2023-05-01 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0008_alter_dictionary_word_uid_alter_user_upk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='upk',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
