# Generated by Django 4.2 on 2023-05-02 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0009_alter_user_upk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
