# Generated by Django 4.2 on 2023-05-02 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0010_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='Catg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webhook.wcategory'),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='word_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webhook.user'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='Catg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='webhook.recategory'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='Catg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='webhook.recategory'),
        ),
        migrations.AlterField(
            model_name='wcategory',
            name='ctg_uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='webhook.user'),
        ),
    ]
